version: "3.4"
services:
    db:
        image: postgres:13-alpine
        restart: always
        container_name: postgresql_racedb
        environment:
            POSTGRES_PASSWORD: 5wHYUQ9qmttpq58EV4EG
        networks:
            racedb:
        hostname: postgresql_db_app
        volumes:
            - ../postgresql-data:/var/lib/postgresql/data
            - ../postgresql-varrun:/var/run/postgresql
            - ../postgresql/setup-master.sh:/docker-entrypoint-initdb.d/setup-master.sh

        command: /entrypoint.sh

networks:
    racedb:

