version: "3.4"
services:
    db:
        image: postgres:11-alpine
        restart: always
        container_name: postgresql_racedb_app
        environment:
            POSTGRES_PASSWORD: 5wHYUQ9qmttpq58EV4EG
        networks:
            racedb:
        hostname: postgresql_db_app.local
        volumes:
            - ./racedb/postgresql-racedb-data:/var/lib/postgresql/data
            - ./racedb/postgresql-racedb-varrun:/var/run/postgresql


volumes:
    postgresql-racedb-data:
    postgresql-racedb-varrun:

networks:
    racedb:


