version: "3.4"
services:

    racedb:
        image: esitarski/racedb:latest
        restart: always
        container_name: racedb_8001_primary
        ports:
            - "8001:8000"
        environment:
            - sqlite3_database_fname:/racedb-data/RaceDB.sqlite3
            - PYTHONPATH:/RaceDB
            - RACEDBLOGFILE:/racedb-data/RaceDB-log.txt
            - TIME_ZONE=America/Vancouver
            - DATETIME_FORMAT=ISO
            - VERBOSITY=1
            #
            # Uncomment to use RFID reader, see ../docker.env
            - RFID_READER_HOST=10.16.29.136
            - RFID_TRANSMIT_POWER=40
            - RFID_RECEIVER_SENSITIVITY=20
            #- LLRP_SERVER_HOST=
        hostname: racedb_8001_primary.local
        networks:
            racedb:
        depends_on:
            - db
        volumes:
            - ../db/${ROLE}/run:/var/run/postgresql
            - ../db/${ROLE}/lib:/var/lib/postgresql
            - ../db/${ROLE}/data:/var/lib/postgresql/data
            - ../racedb/.nobackup:/racedb-data/.nobackup
            #- ../test.json:/racedb-data/test.json
            - ../racedb/02-postgres.sh:/docker-entrypoint-init.d/02-postgres.sh
            - ../racedb/94-setsuper.sh:/docker-entrypoint-init.d/94-setsuper.sh
            - ../racedb/check.sh:/check.sh
            - ../racedb/simple.py:/simple.py
            - ../racedb/print_bib.py:/RaceDB/core/print_bib.py
            - ../racedb/index.html:/var/local/www/index.html

