version: "3.4"
services:

    racedb:
        image: esitarski/racedb:latest
        restart: always
        container_name: racedb_8080
        ports:
            - "8080:8000"
        environment:
            - sqlite3_database_fname:/racedb-data/RaceDB.sqlite3
            - PYTHONPATH:/RaceDB
            - RACEDBLOGFILE:/racedb-data/RaceDB-log.txt
            - TIME_ZONE=America/Vancouver
            - DATETIME_FORMAT=ISO
            - VERBOSITY=1
        #env_file:
        #    - ../racedb.env
        hostname: racedb_8080.local
        networks:
            racedb:
        depends_on:
            - db
        volumes:
            - ../postgresql-varrun:/var/run/postgresql
            - ../.nobackup:/racedb-data/.nobackup
            - ../test.json:/racedb-data/test.json

